# permissions for end users to view grafanacontactpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: grafanacontactpoint-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: grafana-operator
    app.kubernetes.io/part-of: grafana-operator
    app.kubernetes.io/managed-by: kustomize
  name: grafanacontactpoint-viewer-role
rules:
- apiGroups:
  - grafana.integreatly.org
  resources:
  - grafanacontactpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - grafana.integreatly.org
  resources:
  - grafanacontactpoints/status
  verbs:
  - get
