# permissions for end users to view grafanaalertrulegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafanaalertrulegroup-viewer-role
rules:
- apiGroups:
  - grafana.integreatly.org
  resources:
  - grafanaalertrulegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - grafana.integreatly.org
  resources:
  - grafanaalertrulegroups/status
  verbs:
  - get
